version: '3'

services:
  zookeeper:
    container_name: zookeeper
    restart: always
    image: wurstmeister/zookeeper:latest
    ports:
      - "2181:2181"
    volumes:
      - /mnt/447fd10c-6bd4-408e-8017-081947b7169e/kafka/zookeeper:/data
  kafka:
    container_name: kafka
    restart: always
    image: wurstmeister/kafka:latest
    ports:
      - "9092:9092"
    volumes:
      - /mnt/447fd10c-6bd4-408e-8017-081947b7169e/kafka/kafka:/kafka
    environment:
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://192.168.56.3:9092
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181

  kafka-ui:
    container_name: kafka-ui
    restart: always
    image: provectuslabs/kafka-ui:latest
    ports:
      - "38080:8080"
    volumes:
      - /mnt/447fd10c-6bd4-408e-8017-081947b7169e/kafka/kafkaui:/data
    environment:
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: 192.168.56.3:9092
      KAFKA_CLUSTERS_0_ZOOKEEPER: zookeeper:2181
      DYNAMIC_CONFIG_ENABLED: 'true'
